const colors = {
  red: "#ac616a",
  green: "#98b386",
  yellow: "#bfa86b",
  blue: "#7ba2c3",
  cyan: "#8ac6c7",
  magenta: "#999dd4",
  background: "var(--soft-background)",
  foreground: "var(--foreground)",
}

const gabriel = {
  lineNumberColor: `#6272a4`,
  lineNumberBgColor: `#282a36`,
  backgroundColor: colors.background,
  operatorColor: colors.red,
  textColor: colors.foreground,
  substringColor: colors.blue,
  keywordColor: colors.red,
  attributeColor: colors.magenta,
  selectorTagColor: `#8be9fd`,
  docTagColor: colors.blue,
  nameColor: `#66d9ef`,
  builtInColor: colors.magenta,
  literalColor: colors.red,
  bulletColor: `#8BE9FD`,
  codeColor: colors.magenta,
  additionColor: colors.blue,
  regexpColor: colors.blue,
  symbolColor: colors.blue,
  variableColor: colors.foreground,
  templateVariableColor: colors.magenta,
  linkColor: `#00bcd4`,
  selectorAttributeColor: colors.blue,
  selectorPseudoColor: colors.blue,
  typeColor: `#8BE9FD`,
  stringColor: colors.blue,
  selectorIdColor: colors.magenta,
  selectorClassColor: colors.magenta,
  quoteColor: colors.blue,
  templateTagColor: colors.foreground,
  deletionColor: colors.red,
  titleColor: `#ff555580`,
  sectionColor: colors.blue,
  commentColor: "#777777",
  metaKeywordColor: colors.magenta,
  metaColor: colors.magenta,
  functionColor: colors.magenta,
  numberColor: `#bd93f9`,
}

export default gabriel
