const colors = {
  red: "#ac616a",
  green: "#98b386",
  yellow: "#bfa86b",
  blue: "#7ba2c3",
  cyan: "#8ac6c7",
  magenta: "#999dd4",
  background: "var(--soft-background)",
  foreground: "var(--foreground)",
  comment: "var(--disabled-foreground)",
}

const gabriel = {
  lineNumberColor: `#6272a4`,
  lineNumberBgColor: `#282a36`,
  backgroundColor: colors.background,
  operatorColor: colors.red,
  textColor: colors.foreground,
  substringColor: colors.blue,
  keywordColor: colors.red,
  attributeColor: colors.magenta,
  selectorTagColor: colors.cyan,
  docTagColor: colors.blue,
  nameColor: colors.blue,
  builtInColor: colors.magenta,
  literalColor: colors.red,
  bulletColor: colors.cyan,
  codeColor: colors.magenta,
  additionColor: colors.blue,
  regexpColor: colors.blue,
  symbolColor: colors.blue,
  variableColor: colors.foreground,
  templateVariableColor: colors.magenta,
  linkColor: colors.blue,
  selectorAttributeColor: colors.blue,
  selectorPseudoColor: colors.blue,
  typeColor: colors.cyan,
  stringColor: colors.blue,
  selectorIdColor: colors.magenta,
  selectorClassColor: colors.magenta,
  quoteColor: colors.blue,
  templateTagColor: colors.foreground,
  deletionColor: colors.red,
  titleColor: colors.red,
  sectionColor: colors.blue,
  commentColor: colors.comment,
  metaKeywordColor: colors.magenta,
  metaColor: colors.magenta,
  functionColor: colors.magenta,
  numberColor: colors.magenta,
}

export default gabriel
